name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "30 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
      - name: push
        uses: actions-x/commit@v2
        with:
          name: Will Pike
          email: willpike00@gmail.commit
          message: Automatically Updated log with github actions