name: Scheduled Health Check

# Controls when the action will run.
on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Uptime Checker
        run: python run.py
      - name: Commit + Push
        uses: actions-x/commit@v2
        with:
          name: Will Pike
          email: willpike00@gmail.com
          files: logs
          message: Automatically Updated log with github actions